[versions]
dailymotion-sdk-version = "2.0.0-snapshot-1-kotlin2.1.21"

[libraries]
dailymotion-sdk = { group = "com.dailymotion.player.android", name = "sdk", version.ref = "dailymotion-sdk-version" }
dailymotion-ads = { group = "com.dailymotion.player.android", name = "ads", version.ref = "dailymotion-sdk-version" }
dailymotion-cast = { group = "com.dailymotion.player.android", name = "cast", version.ref = "dailymotion-sdk-version" }
